### ISSUE TITLE
Multiple instances monitoring  on the same server

### ISSUE THREAD

**Issue by slavikvin** [kxepal/munin-plugin-couchdb#2]
Hi, I am running 3 couchdb instances on the same sever and trying to add munin monitoring features for all of them using your plugin. I tried to separate them by title, but my munin server have some collisions with that :( Can you recommend me something? Any helpful information would be appreciated.

**Comment by kxepal** [comment]
Hi,
Solution for you should be something like that:
1. Place couchdb_ munin script somewhere
2. Create symlinks against it in plugins.d/ directory like couchdb_instance_1, couchdb_instance_2 etc.
3. In conf.d/ create a file with configuration for the each:
```
[couchdb_instance_1]
env.uri    http://localhost:59841

[couchdb_instance_2]
env.uri    http://localhost:59842

...
```
and with additional options as well by your need.

Thought, didn't test such setup, but should works.

**Comment by slavikvin** [comment]
Thanks for quick answer, just tried out your solution, the munin server cgi shows separate graphs for database fragmentation and database documents, but all the  graphs are in single example , it seems that data from all instances writing to same rrds, except the  database fragmentation and database documents which include database name in metric name. Any suggestion?

**Comment by kxepal** [comment]
Hm, indeed it will because all the graphs will have the same name - I miss that moment. Then worth to fix that (:

**Comment by kxepal** [comment]
Also, let's move this feature request to original repo: https://github.com/gws/munin-plugin-couchdb as it's the base one and I have commit bit there to handle your needs.

**Comment by myroslav** [comment]
This issue was moved to gws/munin-plugin-couchdb#2

**Comment by kxepal** [comment]
@myroslav What's the magic! Thank you. Closing this then.

**Comment by myroslav** [comment]
https://github-issue-mover.appspot.com/ is my friend :)

**Comment by kxepal** [comment]
Good to know! Thanks for sharing (:
